# Generated by Django 5.1.1 on 2025-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="order", field=models.IntegerField(default=10),
        ),
    ]
