# Generated by Django 5.1.1 on 2025-08-02 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(2000)]
            ),
        ),
    ]
